FROM python:3.11-slim

WORKDIR /app

COPY ./embed-api .

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.api.v1.main:app", "--host", "0.0.0.0", "--port", "8801"]